/**
 * This is autogenerated Typst markup from a Matplotlib Typst renderer. This
 * markup is used to measure shape of a textual content.
 *
 * Timestamp: {{ date }}.
 */

#let font-family = "{{ family }}"
#let font-size = {{ size }}pt
#let content = [{{ content }}]

#set page(width: auto, height: auto, margin: 0pt)
#set text(font: font-family, size: font-size, top-edge: "ascender")

#let sizeof(it) = style(styles => {
  let shape = measure(it, styles)
  return (shape.width, shape.height)
})

#sizeof(text(bottom-edge: "baseline", content))
#sizeof(text(bottom-edge: "descender", content))
